FROM node:latest

ENV PARSE_HOME /parse
ENV PARSE_CLOUD /parse/parse-cloud

ADD index.js ${PARSE_HOME}/index.js
ADD package.json ${PARSE_HOME}/package.json
ADD jsconfig.json ${PARSE_HOME}/jsconfig.json

COPY parse-cloud $PARSE_CLOUD

WORKDIR $PARSE_HOME
RUN npm install

## ENV
#ENV APP_ID myAppId
#ENV MASTER_KEY myMasterKey
#ENV DATABASE_URI mongodb://localhost:27017/dev
#ENV CLOUD_HOME ${PARSE_CLOUD}/parse-cloud
#ENV PARSE_MOUNT /parse
#ENV COLLECTION_PREFIX
#ENV CLIENT_KEY
#ENV REST_API_KEY
#ENV DOTNET_KEY
#ENV JAVASCRIPT_KEY
#ENV DOTNET_KEY
#ENV FILE_KEY
#ENV FACEBOOK_APP_IDS "xx,xxx"

ENV PARSE_PORT 1337
ENV PUBLIC_PORT 1338

EXPOSE $PARSE_PORT
EXPOSE $PUBLIC_PORT

VOLUME $PARSE_CLOUD
ENV NODE_PATH .

CMD [ "npm", "start" ]
